export const categories = ["All", "Beauty", "Cognitive", "Digestive", "Sleep", "Wellness"];

export interface Product {
  id: string;
  variantId: string;
  price: number;
  name: string;
  tagline: string;
  category: string;
  original: string;
  flavor: string;
  color: string;
  ingredients: string;
  amount: string;
  description: string;
  benefits: string[];
  badges: string[];
}

export const products: Product[] = [
  {
    id: "recover", variantId: "51701265465560", price: 36.5,
    name: "Recover Stripd",
    tagline: "The morning after, handled.",
    category: "Wellness",
    original: "Hangover Strips",
    flavor: "Mango-Orange",
    color: "#FF6B35",
    ingredients: "Curcuma Longa, Andrographis, Phyllanthus Niruri, Phyllanthus Emblica, Vitis Vinifera, Cichorium Intybus",
    amount: "30 oral strips",
    description: "Our Hangover Oral Strips are crafted with a blend of ingredients inspired by traditional Ayurvedic practices, designed to support general wellness. These strips help maintain normal fluid balance, support a healthy inflammatory response, and promote liver wellness after a night out.",
    benefits: ["Natural rescue for multiple symptoms", "Healthy inflammatory response", "Liver protection and support", "Supports normal fluid balance"],
    badges: ["Gluten-free", "Vegan friendly", "Halal", "Non-GMO"],
  },
  {
    id: "glow", variantId: "51701263761624", price: 32.9,
    name: "Glow Stripd",
    tagline: "Beauty that dissolves on your tongue.",
    category: "Beauty",
    original: "Hair, Skin and Nails Strips",
    flavor: "Orange",
    color: "#FF9F1C",
    ingredients: "Biotin 5,000mcg, Folate 400mcg, Vitamin D3 20mcg",
    amount: "30 oral strips",
    description: "Nourish your natural beauty from within with our Hair, Skin and Nails Strips. Each quick-dissolving orange-flavored strip delivers 5,000mcg of Biotin plus Folate and Vitamin D3 to support normal hair strength, skin vitality, and nail health as part of your daily routine.",
    benefits: ["Biotin for Beauty Support", "Folate for Cellular Wellness", "Daily Sunshine in a Strip", "Tasty, On-the-Go Care"],
    badges: ["Gluten-free", "All natural", "Cruelty Free", "Hormone-free"],
  },
  {
    id: "renew", variantId: "51701259206872", price: 28.9,
    name: "Renew Stripd",
    tagline: "Collagen simplified.",
    category: "Beauty",
    original: "Beauty + Collagen Strips",
    flavor: "Mango",
    color: "#FFB347",
    ingredients: "Collagen Peptide 100mg, Vitamin E 6mg",
    amount: "30 oral strips",
    description: "Discover a simple way to support your daily beauty routine. Each strip delivers Collagen Peptides and Vitamin E, two well-known ingredients that help promote the normal health and appearance of skin, hair, and nails. Quick-dissolving mango flavor — no water needed.",
    benefits: ["Promotes Skin Elasticity", "Antioxidant Support", "Supports Healthy Hair & Nails", "Delicious, Mess-Free Beauty"],
    badges: ["Lactose-free", "Hormone-free", "All natural", "No fillers"],
  },
  {
    id: "focus", variantId: "51701258059992", price: 39.0,
    name: "Focus Stripd",
    tagline: "Mushroom-powered clarity.",
    category: "Cognitive",
    original: "Mushroom Focus Strips",
    flavor: "Chocolate",
    color: "#8B4513",
    ingredients: "Lion's Mane 30mg, Maitake 25mg, Cordyceps 25mg, Shiitake 20mg",
    amount: "30 oral strips",
    description: "Stay sharp and centered with our Mushroom Focus Strips. Each smooth chocolate-flavored strip delivers a curated blend of Lion's Mane, Maitake, Cordyceps, and Shiitake mushrooms — traditionally valued for promoting normal cognitive function, stamina, and daily vitality.",
    benefits: ["Cognitive Support from Lion's Mane", "Stamina-Promoting Cordyceps", "Maitake & Shiitake Wellness Boost", "Chocolate Flavor, Zero Fuss"],
    badges: ["Gluten-free", "Vegetarian", "All natural", "Alcohol Free"],
  },
  {
    id: "passion", variantId: "51701256552664", price: 37.9,
    name: "Passion Stripd",
    tagline: "Vitality, recharged.",
    category: "Wellness",
    original: "Libido Support Strips",
    flavor: "Chocolate",
    color: "#C0392B",
    ingredients: "Cordyceps Militaris 50mg, Shilajit 50mg, Oyster Peptide 20mg",
    amount: "30 oral strips",
    description: "Add extra vitality to your wellness routine. Each rich chocolate-flavored strip delivers Cordyceps militaris, Shilajit, and Oyster Peptide — ingredients traditionally valued for supporting normal endurance, energy metabolism, and sexual wellness as part of a balanced lifestyle.",
    benefits: ["Cordyceps for Active Vitality", "Marine-Derived Peptides", "Shilajit's Natural Support", "Rich Chocolate Flavor"],
    badges: ["Gluten-free", "Hormone-free", "Antibiotic-free", "Cruelty Free"],
  },
  {
    id: "gut", variantId: "51701268087000", price: 39.0,
    name: "Gut Stripd",
    tagline: "10 billion allies on your tongue.",
    category: "Digestive",
    original: "Probiotic + Metabolism Strips",
    flavor: "Mixed Berry",
    color: "#9B59B6",
    ingredients: "Polydextrose 50mg, Bifidobacterium lactis 37.5mg (10B CFU)",
    amount: "30 oral strips",
    description: "Support your digestive wellness effortlessly. Each strip contains Bifidobacterium lactis — 10 billion CFU — plus prebiotic polydextrose to help maintain a healthy balance of gut bacteria. Dissolves on your tongue in seconds with a refreshing mixed berry flavor.",
    benefits: ["Daily Digestive Support", "Probiotic + Prebiotic Synergy", "Anytime, Anywhere Convenience", "Refreshing Flavor Experience"],
    badges: ["Gluten-free", "All natural", "Antibiotic-free", "Cruelty Free"],
  },
  {
    id: "bone", variantId: "51701254455512", price: 28.9,
    name: "Bone Stripd",
    tagline: "Strength from within.",
    category: "Wellness",
    original: "Bone Support Strips",
    flavor: "Raspberry",
    color: "#E74C3C",
    ingredients: "Vitamin D3 2000 IU, Vitamin K2 120mcg",
    amount: "30 oral strips",
    description: "Support your body's natural bone health processes with Vitamin D3 and Vitamin K2. These essential nutrients work together to help maintain normal calcium absorption and bone maintenance. Each delicious raspberry-flavored strip dissolves quickly — no water required.",
    benefits: ["Essential for Bone Support", "Supports Bone Strength", "Perfect for On-the-Go", "Helps Maintain Normal Immune Function"],
    badges: ["Gluten-free", "All natural", "Antibiotic-free", "No fillers"],
  },
  {
    id: "digest", variantId: "51701232959704", price: 35.9,
    name: "Digest Stripd",
    tagline: "Your gut's second brain.",
    category: "Digestive",
    original: "Digestive + Gut Health Strips",
    flavor: "Mixed Berry",
    color: "#6C5CE7",
    ingredients: "Bacillus Coagulans 10B CFU, Protease, Papain, Bromelain",
    amount: "30 oral strips",
    description: "Formulated with Bacillus Coagulans and digestive enzymes to support normal gut balance and aid natural protein digestion. These fast-dissolving strips make gut health simple — one mixed berry strip a day, no water needed.",
    benefits: ["Supports Normal Gut Balance", "Aids Natural Protein Digestion", "Fast-Dissolving Convenience", "Gut Health Made Simple"],
    badges: ["Gluten-free", "Vegetarian", "All natural", "Cruelty Free"],
  },
  {
    id: "power", variantId: "51701251768536", price: 36.5,
    name: "Power Stripd",
    tagline: "Clean energy without the crash.",
    category: "Cognitive",
    original: "Energy Strips",
    flavor: "Cranberry",
    color: "#FF0055",
    ingredients: "L-Theanine, Caffeine, Vitamin B12 (Methylcobalamin)",
    amount: "30 oral strips",
    description: "Sustained energy and mental clarity in a quick-dissolving strip. Formulated with L-Theanine, Caffeine, and Vitamin B12 for enhanced focus and physical endurance without the jitters or crash.",
    benefits: ["Enhanced focus", "Increased physical endurance", "Mental clarity", "Sustained energy without crashes"],
    badges: ["Gluten-free", "Vegetarian", "Non-GMO", "No fillers"],
  },
  {
    id: "rest", variantId: "51701228765400", price: 36.5,
    name: "Rest Stripd",
    tagline: "Sleep without the grogginess.",
    category: "Sleep",
    original: "Sleep Strips",
    flavor: "Raspberry",
    color: "#5B8DEF",
    ingredients: "Valerian Root, Lavender, Chamomile, Hibiscus, Melatonin",
    amount: "30 oral strips",
    description: "A non-addictive sleep aid formulated with Valerian Root, Lavender, Chamomile, and Melatonin. These fast-dissolving strips help enhance sleep quality and promote overall well-being so you wake up refreshed — not groggy.",
    benefits: ["Enhanced sleep quality", "Overall well-being", "Increased energy levels", "Non-addictive sleep aid"],
    badges: ["Gluten-free", "Vegan friendly", "Halal", "Non-GMO"],
  },
  {
    id: "iron", variantId: "51701251113176", price: 28.9,
    name: "Iron Stripd",
    tagline: "Oxygen in a strip.",
    category: "Wellness",
    original: "Iron Strips",
    flavor: "Raspberry",
    color: "#E84393",
    ingredients: "Iron 19mg (Ferric Saccharate), Folate 400mcg",
    amount: "30 oral strips",
    description: "Gentle iron supplementation in a convenient strip format. Each delicious raspberry-flavored strip delivers 19mg of Iron plus Folate to support healthy red blood cell formation and everyday energy levels.",
    benefits: ["Gentle, Convenient Format", "Delicious Raspberry Flavor", "Folate for Healthy Cell Support", "Iron for Everyday Energy"],
    badges: ["Gluten-free", "Vegetarian", "All natural", "Cruelty Free"],
  },
  {
    id: "balance", variantId: "51701267890392", price: 35.9,
    name: "Balance Stripd",
    tagline: "Mindful eating, simplified.",
    category: "Wellness",
    original: "Appetite Balance & Weight Support Strips",
    flavor: "Mixed Berry",
    color: "#00CEC9",
    ingredients: "Chromium 75mcg, Molybdenum 10mcg, Saffron 10mg",
    amount: "30 oral strips",
    description: "Nutrient support for daily wellness featuring Chromium, Molybdenum, and Saffron. These convenient strips help maintain normal blood sugar levels and support mindful eating habits as part of a balanced lifestyle.",
    benefits: ["Nutrient Support for Daily Wellness", "Botanical Support for Balance", "Helps Maintain Normal Blood Sugar", "Convenient On-the-Go Format"],
    badges: ["Gluten-free", "Vegan friendly", "Antibiotic-free", "Alcohol Free"],
  },
  {
    id: "calm", variantId: "51701233778904", price: 32.9,
    name: "Calm Stripd",
    tagline: "Find your center, instantly.",
    category: "Cognitive",
    original: "Cognitive Relax Strips",
    flavor: "Strawberry-Peppermint",
    color: "#A8E6CF",
    ingredients: "L-Theanine 50mg, GABA 25mg, Vitamin B6 6mg",
    amount: "30 oral strips",
    description: "Supports a calm, focused mind with L-Theanine, GABA, and Vitamin B6. These quick-dissolving strips encourage mental wellbeing and promote nervous system wellness — anytime you need to find your center.",
    benefits: ["Supports a Calm, Focused Mind", "Encourages Mental Wellbeing", "Promotes Nervous System Wellness", "Quick-Dissolving, Anytime Support"],
    badges: ["Gluten-free", "Vegan friendly", "All natural", "No fillers"],
  },
];
